name:                toy-language
version:             0.1.0.0
github:              "MurakamiKennzo/toy-language"
license:             MIT
author:              "murakami"
maintainer:          "w18191263056@yahoo.co.jp"
copyright:           "2020 murakami"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MurakamiKennzo/toy-language#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- haskeline
- mtl

library:
  source-dirs: src

executables:
  toy-language-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-language

tests:
  toy-language-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-language
